twig:
    file_name_pattern: '*.twig'
    form_themes:
        # Renders all forms with Bootstrap 5 markup automatically.
        - 'bootstrap_5_layout.html.twig'

when@test:
    twig:
        strict_variables: true
