<?php

namespace App\Entity;

use App\Repository\QuizQuestionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * A "What? Where? When?" style question generated by the app
 * and submitted (or prepared as a draft) to the tvigra.ru editors.
 */
#[ORM\Entity(repositoryClass: QuizQuestionRepository::class)]
class QuizQuestion
{
    public const SOURCE_AI = 'ai';
    public const SOURCE_LOCAL = 'local';

    public const CHANNEL_DRAFT = 'draft';
    public const CHANNEL_EMAIL = 'email';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $question = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $answer = null;

    /** Verifiable source: book (author, title, publisher, year, page) or link. */
    #[ORM\Column(type: Types::TEXT)]
    private ?string $source = null;

    /** QuizQuestion::SOURCE_* */
    #[ORM\Column(length: 16)]
    private ?string $sourceType = self::SOURCE_LOCAL;

    /** QuizQuestion::CHANNEL_* */
    #[ORM\Column(length: 16)]
    private ?string $channel = self::CHANNEL_DRAFT;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $sentAt = null;

    public function __construct(string $question, string $answer, string $source, string $sourceType)
    {
        $this->question = $question;
        $this->answer = $answer;
        $this->source = $source;
        $this->sourceType = $sourceType;
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function getAnswer(): ?string
    {
        return $this->answer;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function getSourceType(): ?string
    {
        return $this->sourceType;
    }

    public function getChannel(): ?string
    {
        return $this->channel;
    }

    public function markSent(string $channel): void
    {
        $this->channel = $channel;
        $this->sentAt = new \DateTimeImmutable();
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getSentAt(): ?\DateTimeImmutable
    {
        return $this->sentAt;
    }
}
